### ISSUE TITLE
Integration with `log` crate facade

### ISSUE THREAD

**Issue by Geobert** [jesusprubio/leg#6]
The Rust logging ecosystem seems to use the `log` crate as the prefered way to expose logging capabilities and then choose a backend for it.

Maybe `leg` should integrate better with `log` so to change logs rendering, we just have to change the backend and not changing all the logs already present.

**Comment by jesusprubio** [comment]
After a long discussion in reddit and HN I decided to keep the library simpler only focusing on the output for CLIs. In fact, I've changed the description of the project.

Thank you!
